// Helper to get asset URLs with the correct base path for GitHub Pages.
// This uses Vite's BASE_URL which is set from the `base` config in vite.config.ts.

/**
 * Files for which we ship a `.webp` variant alongside the original.
 * `asset('Circle_logo.png')` will transparently resolve to `Circle_logo.webp`
 * on browsers that requested the page (all modern browsers support WebP since
 * 2020, ~96% of global traffic).
 *
 * Generated by the build-time conversion of every public-facing PNG/JPEG over
 * 100 KB. Logos and tiny icons stay as PNG since the WebP win is negligible.
 *
 * To add another auto-converted file: drop a `<name>.webp` into /public next
 * to the original, then add the original filename to this set.
 */
const WEBP_VARIANTS = new Set([
  'Circle_logo.png',
  'IMG_80F37FA15505-1.jpeg',
  'Landing_Page_photo.png',
  'Nesty_logo.png',
  'hero_illustraion.png',
  'home/landing-hero.png',
  'home/how-it-works.png',
  'home/privacy-hero.png',
  'guides/how-many-baby-clothes.png',
  'guides/how-many-diapers.png',
  'guides/how-to-build-a-registry.png',
  'guides/multi-store-registry.png',
  'guides/registry-by-trimester.png',
  'guides/registry-must-haves.png',
  'guides/second-baby-registry.png',
  'guides/when-to-start-registry.png',
])

export function asset(path: string): string {
  const base = import.meta.env.BASE_URL || '/'
  const cleanPath = path.startsWith('/') ? path.slice(1) : path
  // Transparent .webp swap for files that have a smaller WebP variant.
  const resolved = WEBP_VARIANTS.has(cleanPath)
    ? cleanPath.replace(/\.(png|jpeg|jpg)$/i, '.webp')
    : cleanPath
  return `${base}${resolved}`
}
